#!/bin/bash


# Set decoration geometry
berryc border_width       0
berryc inner_border_width 1
berryc title_height       25
berryc top_gap            20

# Set decoration colors
berryc focus_color         3B4252
berryc unfocus_color       3B4252
berryc inner_focus_color   4C566A
berryc inner_unfocus_color 4C566A
berryc text_focus_color    4C566A
berryc text_unfocus_color  4C566A

# Other options
berryc smart_place "true"
berryc draw_text   "true"
berryc edge_lock   "true"
berryc set_font    "Dina-9"


sxhkd
nitrogen --restore
